safe:        true
port:        4000
baseurl:     /
permalink:   pretty
exclude: ['images']
#Setup
title:       Simon Chen
img:         /assets/profile-picture.jpg
tagline:     'Welcome to my personal website! Feel free to waste time here. Updated weekly.'
url:         http://localhost:4000
future:      true

color:
  primary: FFDC00 #yellow
  secondary: 428BCA #twitter blue

navigation:
- text: BLOG
  url: /blog/
  glyph: 'glyphicon glyphicon-comment'
  color: orange
- text: PORTFOLIO
  url: /portfolio/
  glyph: 'glyphicon glyphicon-camera'
  color: blue
- text: PROJECTS
  url: /projects/
  glyph: 'glyphicon glyphicon-folder-open' 
  layout: default
  color: orange
- text: SITES
  url: /sites/
  glyph: 'glyphicon glyphicon-cloud'
  color: blue
- text: ABOUT
  url: /about/
  glyph: 'glyphicon glyphicon-user'
  color: orange

other-sites:
- text: flickr
  url: https://www.flickr.com/photos/floatingon
- text: 500px
  url: http://500px.com/SimonChen1
- text: Simon Chen Photography
  url: https://www.facebook.com/simonchenphotography

footer-links:
- url: http://github.com/simonc312
  img: /assets/github1.png
- url: http://twitter.com/Simonchen312
  img: /assets/twitter1.png
- url: http://www.linkedin.com/in/simonc312
  img: /assets/linkedin1.png

# Social networks usernames
social:
  - title: twitter
    url: https://twitter.com/Simonchen312
  - title: linkedin
    url: https://www.linkedin.com/in/simonc312
  - title: github
    url: http://github.com/simonc312

sass:
  sass_dir: _sass
  style: compressed

collections:
  portfolio:
      output: true
      permalink: /portfolio/:path/
  projects:
      output: true
      permalink: /projects/:path/

defaults: 
  - scope:
      path: ""
    values:
      layout: "default"
      type: "pages"

  - scope:
      path: "portfolio"
      type: "pages"
    values:
      layout: "default" 
      author: "Simon Chen"
      category: "portfolio"