safe:        true
port:        4000
baseurl:     /
permalink:   pretty
exclude: ['images']
#Setup
title:       Simon Chen
tagline:     'Welcome to my personal website! Feel free to waste time here. Updated weekly.'
subscribe:   Subscribe
url:         http://localhost:4000
future:      true
collections:
  portfolio:
      output: true
      permalink: /portfolio/:path/
  projects:
      output: true
      permalink: /projects/:path/
defaults: 
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "portfolio"
      type: "page"
    values:
      layout: "default" # overrides previous default layout
      author: "Simon Chen"
      category: "portfolio"