safe:        true
port:        4000
baseurl:     /
permalink:   pretty
exclude: ['images']
#Setup
title:       Simon Chen
img:         /assets/profile-picture.jpg
tagline:     'Welcome to my personal website! Feel free to waste time here. Updated weekly.'
subscribe:   Subscribe
url:         http://localhost:4000
future:      true

navigation:
- text: BLOG
  url: /blog/
  glyph: 'glyphicon glyphicon-comment'
  color: orange
- text: PORTFOLIO
  url: /portfolio/
  glyph: 'glyphicon glyphicon-camera'
  color: blue
- text: PROJECTS
  url: /projects/
  glyph: 'glyphicon glyphicon-folder-open' 
  layout: default
  color: orange
- text: ABOUT
  url: /about/
  glyph: 'glyphicon glyphicon-user'
  color: blue
- text: SITES
  url: /sites/
  glyph: 'glyphicon glyphicon-cloud'
  color: orange

project-sites:
- text: Programming Language Paradigm Map with D3
  url: /d3-programming-lang-vis
- text: SF Crime Data Analysis with Google Maps API
  url: /google-maps-sf-crime-vis
- text: Projects That Work Ruby on Rails Application
  url: http://projects-that-work.herokuapp.com/
- text: (New) Start Up Ciao's Landing Page
  url: http://www.joinciao.com

other-sites:
- text: flickr
  url: https://www.flickr.com/photos/floatingon
- text: 500px
  url: http://500px.com/SimonChen1
- text: Simon Chen Photography
  url: https://www.facebook.com/simonchenphotography

footer-links:
- url: http://github.com/simonc312
  img: /assets/github1.png
- url: http://twitter.com/Simonchen312
  img: /assets/twitter1.png
- url: http://www.linkedin.com/in/simonc312
  img: /assets/linkedin1.png

collections:
  portfolio:
      output: true
      permalink: /portfolio/:path/
  projects:
      output: true
      permalink: /projects/:path/
defaults: 
  - scope:
      path: ""
    values:
      layout: "default"
      type: "pages"

  - 
    scope:
      path: "/projects/sf_crime/"
    values:
      layout: "SFcrime"
      category: "projects"
  -
    scope:
      path: "portfolio"
      type: "pages"
    values:
      layout: "default" # overrides previous default layout
      author: "Simon Chen"
      category: "portfolio"